# Generated by Django 5.1 on 2025-03-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_blerb_title_remove_blerb_active_members_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='gallery_names',
        ),
        migrations.DeleteModel(
            name='blerb',
        ),
    ]
