# Generated by Django 5.1 on 2025-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='testing', max_length=500),
            preserve_default=False,
        ),
    ]
